export const PLACE_TYPE_TO_CATEGORY: Record<string, string> = {
  // Automotive
  car_dealer: "🚗 Automotive",
  car_rental: "🚗 Automotive",
  car_repair: "🚗 Automotive",
  car_wash: "🚗 Automotive",
  ebike_charging_station: "🚗 Automotive",
  electric_vehicle_charging_station: "🚗 Automotive",
  gas_station: "🚗 Automotive",
  parking: "🚗 Automotive",
  parking_garage: "🚗 Automotive",
  parking_lot: "🚗 Automotive",
  rest_stop: "🚗 Automotive",
  tire_shop: "🚗 Automotive",
  truck_dealer: "🚗 Automotive",

  // Business
  business_center: "💼 Business",
  corporate_office: "💼 Business",
  coworking_space: "💼 Business",
  farm: "💼 Business",
  manufacturer: "💼 Business",
  ranch: "💼 Business",
  supplier: "💼 Business",
  television_studio: "💼 Business",

  // Culture
  art_gallery: "🎨 Culture",
  art_museum: "🎨 Culture",
  art_studio: "🎨 Culture",
  auditorium: "🎨 Culture",
  castle: "🎨 Culture",
  cultural_landmark: "🎨 Culture",
  fountain: "🎨 Culture",
  historical_place: "🎨 Culture",
  history_museum: "🎨 Culture",
  monument: "🎨 Culture",
  museum: "🎨 Culture",
  performing_arts_theater: "🎨 Culture",
  sculpture: "🎨 Culture",

  // Education
  academic_department: "📚 Education",
  educational_institution: "📚 Education",
  library: "📚 Education",
  preschool: "📚 Education",
  primary_school: "📚 Education",
  research_institute: "📚 Education",
  school: "📚 Education",
  secondary_school: "📚 Education",
  university: "📚 Education",

  // Entertainment and Recreation
  adventure_sports_center: "🎉 Entertainment and Recreation",
  amphitheatre: "🎉 Entertainment and Recreation",
  amusement_center: "🎉 Entertainment and Recreation",
  amusement_park: "🎉 Entertainment and Recreation",
  aquarium: "🎉 Entertainment and Recreation",
  banquet_hall: "🎉 Entertainment and Recreation",
  barbecue_area: "🎉 Entertainment and Recreation",
  botanical_garden: "🎉 Entertainment and Recreation",
  bowling_alley: "🎉 Entertainment and Recreation",
  casino: "🎉 Entertainment and Recreation",
  childrens_camp: "🎉 Entertainment and Recreation",
  city_park: "🎉 Entertainment and Recreation",
  comedy_club: "🎉 Entertainment and Recreation",
  community_center: "🎉 Entertainment and Recreation",
  concert_hall: "🎉 Entertainment and Recreation",
  convention_center: "🎉 Entertainment and Recreation",
  cultural_center: "🎉 Entertainment and Recreation",
  cycling_park: "🎉 Entertainment and Recreation",
  dance_hall: "🎉 Entertainment and Recreation",
  dog_park: "🎉 Entertainment and Recreation",
  event_venue: "🎉 Entertainment and Recreation",
  ferris_wheel: "🎉 Entertainment and Recreation",
  garden: "🎉 Entertainment and Recreation",
  go_karting_venue: "🎉 Entertainment and Recreation",
  hiking_area: "🎉 Entertainment and Recreation",
  historical_landmark: "🎉 Entertainment and Recreation",
  indoor_playground: "🎉 Entertainment and Recreation",
  internet_cafe: "🎉 Entertainment and Recreation",
  karaoke: "🎉 Entertainment and Recreation",
  live_music_venue: "🎉 Entertainment and Recreation",
  marina: "🎉 Entertainment and Recreation",
  miniature_golf_course: "🎉 Entertainment and Recreation",
  movie_rental: "🎉 Entertainment and Recreation",
  movie_theater: "🎉 Entertainment and Recreation",
  national_park: "🎉 Entertainment and Recreation",
  night_club: "🎉 Entertainment and Recreation",
  observation_deck: "🎉 Entertainment and Recreation",
  off_roading_area: "🎉 Entertainment and Recreation",
  opera_house: "🎉 Entertainment and Recreation",
  paintball_center: "🎉 Entertainment and Recreation",
  park: "🎉 Entertainment and Recreation",
  philharmonic_hall: "🎉 Entertainment and Recreation",
  picnic_ground: "🎉 Entertainment and Recreation",
  planetarium: "🎉 Entertainment and Recreation",
  plaza: "🎉 Entertainment and Recreation",
  roller_coaster: "🎉 Entertainment and Recreation",
  skateboard_park: "🎉 Entertainment and Recreation",
  state_park: "🎉 Entertainment and Recreation",
  tourist_attraction: "🎉 Entertainment and Recreation",
  video_arcade: "🎉 Entertainment and Recreation",
  vineyard: "🎉 Entertainment and Recreation",
  visitor_center: "🎉 Entertainment and Recreation",
  water_park: "🎉 Entertainment and Recreation",
  wedding_venue: "🎉 Entertainment and Recreation",
  wildlife_park: "🎉 Entertainment and Recreation",
  wildlife_refuge: "🎉 Entertainment and Recreation",
  zoo: "🎉 Entertainment and Recreation",

  // Facilities
  public_bath: "🏢 Facilities",
  public_bathroom: "🏢 Facilities",
  stable: "🏢 Facilities",

  // Finance
  accounting: "💰 Finance",
  atm: "💰 Finance",
  bank: "💰 Finance",

  // Food and Drink (FULL)
  acai_shop: "🍽️ Food and Drink",
  afghani_restaurant: "🍽️ Food and Drink",
  african_restaurant: "🍽️ Food and Drink",
  american_restaurant: "🍽️ Food and Drink",
  argentinian_restaurant: "🍽️ Food and Drink",
  asian_fusion_restaurant: "🍽️ Food and Drink",
  asian_restaurant: "🍽️ Food and Drink",
  australian_restaurant: "🍽️ Food and Drink",
  austrian_restaurant: "🍽️ Food and Drink",
  bagel_shop: "🍽️ Food and Drink",
  bakery: "🍽️ Food and Drink",
  bangladeshi_restaurant: "🍽️ Food and Drink",
  bar: "🍽️ Food and Drink",
  bar_and_grill: "🍽️ Food and Drink",
  barbecue_restaurant: "🍽️ Food and Drink",
  basque_restaurant: "🍽️ Food and Drink",
  bavarian_restaurant: "🍽️ Food and Drink",
  beer_garden: "🍽️ Food and Drink",
  belgian_restaurant: "🍽️ Food and Drink",
  bistro: "🍽️ Food and Drink",
  brazilian_restaurant: "🍽️ Food and Drink",
  breakfast_restaurant: "🍽️ Food and Drink",
  brewery: "🍽️ Food and Drink",
  brewpub: "🍽️ Food and Drink",
  british_restaurant: "🍽️ Food and Drink",
  brunch_restaurant: "🍽️ Food and Drink",
  buffet_restaurant: "🍽️ Food and Drink",
  burmese_restaurant: "🍽️ Food and Drink",
  burrito_restaurant: "🍽️ Food and Drink",
  cafe: "🍽️ Food and Drink",
  cafeteria: "🍽️ Food and Drink",
  cajun_restaurant: "🍽️ Food and Drink",
  cake_shop: "🍽️ Food and Drink",
  californian_restaurant: "🍽️ Food and Drink",
  cambodian_restaurant: "🍽️ Food and Drink",
  candy_store: "🍽️ Food and Drink",
  cantonese_restaurant: "🍽️ Food and Drink",
  caribbean_restaurant: "🍽️ Food and Drink",
  cat_cafe: "🍽️ Food and Drink",
  chicken_restaurant: "🍽️ Food and Drink",
  chicken_wings_restaurant: "🍽️ Food and Drink",
  chilean_restaurant: "🍽️ Food and Drink",
  chinese_noodle_restaurant: "🍽️ Food and Drink",
  chinese_restaurant: "🍽️ Food and Drink",
  chocolate_factory: "🍽️ Food and Drink",
  chocolate_shop: "🍽️ Food and Drink",
  cocktail_bar: "🍽️ Food and Drink",
  coffee_roastery: "🍽️ Food and Drink",
  coffee_shop: "🍽️ Food and Drink",
  coffee_stand: "🍽️ Food and Drink",
  colombian_restaurant: "🍽️ Food and Drink",
  confectionery: "🍽️ Food and Drink",
  croatian_restaurant: "🍽️ Food and Drink",
  cuban_restaurant: "🍽️ Food and Drink",
  czech_restaurant: "🍽️ Food and Drink",
  danish_restaurant: "🍽️ Food and Drink",
  deli: "🍽️ Food and Drink",
  dessert_restaurant: "🍽️ Food and Drink",
  dessert_shop: "🍽️ Food and Drink",
  dim_sum_restaurant: "🍽️ Food and Drink",
  diner: "🍽️ Food and Drink",
  dog_cafe: "🍽️ Food and Drink",
  donut_shop: "🍽️ Food and Drink",
  dumpling_restaurant: "🍽️ Food and Drink",
  dutch_restaurant: "🍽️ Food and Drink",
  eastern_european_restaurant: "🍽️ Food and Drink",
  ethiopian_restaurant: "🍽️ Food and Drink",
  european_restaurant: "🍽️ Food and Drink",
  falafel_restaurant: "🍽️ Food and Drink",
  family_restaurant: "🍽️ Food and Drink",
  fast_food_restaurant: "🍽️ Food and Drink",
  filipino_restaurant: "🍽️ Food and Drink",
  fine_dining_restaurant: "🍽️ Food and Drink",
  fish_and_chips_restaurant: "🍽️ Food and Drink",
  fondue_restaurant: "🍽️ Food and Drink",
  food_court: "🍽️ Food and Drink",
  french_restaurant: "🍽️ Food and Drink",
  fusion_restaurant: "🍽️ Food and Drink",
  gastropub: "🍽️ Food and Drink",
  german_restaurant: "🍽️ Food and Drink",
  greek_restaurant: "🍽️ Food and Drink",
  gyro_restaurant: "🍽️ Food and Drink",
  halal_restaurant: "🍽️ Food and Drink",
  hamburger_restaurant: "🍽️ Food and Drink",
  hawaiian_restaurant: "🍽️ Food and Drink",
  hookah_bar: "🍽️ Food and Drink",
  hot_dog_restaurant: "🍽️ Food and Drink",
  hot_dog_stand: "🍽️ Food and Drink",
  hot_pot_restaurant: "🍽️ Food and Drink",
  hungarian_restaurant: "🍽️ Food and Drink",
  ice_cream_shop: "🍽️ Food and Drink",
  indian_restaurant: "🍽️ Food and Drink",
  indonesian_restaurant: "🍽️ Food and Drink",
  irish_pub: "🍽️ Food and Drink",
  irish_restaurant: "🍽️ Food and Drink",
  israeli_restaurant: "🍽️ Food and Drink",
  italian_restaurant: "🍽️ Food and Drink",
  japanese_curry_restaurant: "🍽️ Food and Drink",
  japanese_izakaya_restaurant: "🍽️ Food and Drink",
  japanese_restaurant: "🍽️ Food and Drink",
  juice_shop: "🍽️ Food and Drink",
  kebab_shop: "🍽️ Food and Drink",
  korean_barbecue_restaurant: "🍽️ Food and Drink",
  korean_restaurant: "🍽️ Food and Drink",
  latin_american_restaurant: "🍽️ Food and Drink",
  lebanese_restaurant: "🍽️ Food and Drink",
  lounge_bar: "🍽️ Food and Drink",
  malaysian_restaurant: "🍽️ Food and Drink",
  meal_delivery: "🍽️ Food and Drink",
  meal_takeaway: "🍽️ Food and Drink",
  mediterranean_restaurant: "🍽️ Food and Drink",
  mexican_restaurant: "🍽️ Food and Drink",
  middle_eastern_restaurant: "🍽️ Food and Drink",
  mongolian_barbecue_restaurant: "🍽️ Food and Drink",
  moroccan_restaurant: "🍽️ Food and Drink",
  noodle_shop: "🍽️ Food and Drink",
  north_indian_restaurant: "🍽️ Food and Drink",
  oyster_bar_restaurant: "🍽️ Food and Drink",
  pakistani_restaurant: "🍽️ Food and Drink",
  pastry_shop: "🍽️ Food and Drink",
  persian_restaurant: "🍽️ Food and Drink",
  peruvian_restaurant: "🍽️ Food and Drink",
  pizza_delivery: "🍽️ Food and Drink",
  pizza_restaurant: "🍽️ Food and Drink",
  polish_restaurant: "🍽️ Food and Drink",
  portuguese_restaurant: "🍽️ Food and Drink",
  pub: "🍽️ Food and Drink",
  ramen_restaurant: "🍽️ Food and Drink",
  restaurant: "🍽️ Food and Drink",
  romanian_restaurant: "🍽️ Food and Drink",
  russian_restaurant: "🍽️ Food and Drink",
  salad_shop: "🍽️ Food and Drink",
  sandwich_shop: "🍽️ Food and Drink",
  scandinavian_restaurant: "🍽️ Food and Drink",
  seafood_restaurant: "🍽️ Food and Drink",
  shawarma_restaurant: "🍽️ Food and Drink",
  snack_bar: "🍽️ Food and Drink",
  soul_food_restaurant: "🍽️ Food and Drink",
  soup_restaurant: "🍽️ Food and Drink",
  south_american_restaurant: "🍽️ Food and Drink",
  south_indian_restaurant: "🍽️ Food and Drink",
  southwestern_us_restaurant: "🍽️ Food and Drink",
  spanish_restaurant: "🍽️ Food and Drink",
  sports_bar: "🍽️ Food and Drink",
  sri_lankan_restaurant: "🍽️ Food and Drink",
  steak_house: "🍽️ Food and Drink",
  sushi_restaurant: "🍽️ Food and Drink",
  swiss_restaurant: "🍽️ Food and Drink",
  taco_restaurant: "🍽️ Food and Drink",
  taiwanese_restaurant: "🍽️ Food and Drink",
  tapas_restaurant: "🍽️ Food and Drink",
  tea_house: "🍽️ Food and Drink",
  tex_mex_restaurant: "🍽️ Food and Drink",
  thai_restaurant: "🍽️ Food and Drink",
  tibetan_restaurant: "🍽️ Food and Drink",
  tonkatsu_restaurant: "🍽️ Food and Drink",
  turkish_restaurant: "🍽️ Food and Drink",
  ukrainian_restaurant: "🍽️ Food and Drink",
  vegan_restaurant: "🍽️ Food and Drink",
  vegetarian_restaurant: "🍽️ Food and Drink",
  vietnamese_restaurant: "🍽️ Food and Drink",
  western_restaurant: "🍽️ Food and Drink",
  wine_bar: "🍽️ Food and Drink",
  winery: "🍽️ Food and Drink",
  yakiniku_restaurant: "🍽️ Food and Drink",
  yakitori_restaurant: "🍽️ Food and Drink",

  // Transportation
  airport: "🚌 Transportation",
  airstrip: "🚌 Transportation",
  bike_sharing_station: "🚌 Transportation",
  bridge: "🚌 Transportation",
  bus_station: "🚌 Transportation",
  bus_stop: "🚌 Transportation",
  ferry_service: "🚌 Transportation",
  ferry_terminal: "🚌 Transportation",
  heliport: "🚌 Transportation",
  international_airport: "🚌 Transportation",
  light_rail_station: "🚌 Transportation",
  park_and_ride: "🚌 Transportation",
  subway_station: "🚌 Transportation",
  taxi_service: "🚌 Transportation",
  taxi_stand: "🚌 Transportation",
  toll_station: "🚌 Transportation",
  train_station: "🚌 Transportation",
  train_ticket_office: "🚌 Transportation",
  tram_stop: "🚌 Transportation",
  transit_depot: "🚌 Transportation",
  transit_station: "🚌 Transportation",
  transit_stop: "🚌 Transportation",
  transportation_service: "🚌 Transportation",
  truck_stop: "🚌 Transportation",
} as const;
